---
# ansible-playbook playbooks/reset-password.yaml -i inventory/hosts --extra-vars new_password=<YOUR_PASSWORD>
- name: Add/Update User Password playbook
  hosts: all
  become: true
  tasks:
  - name: Add Password for User created in playbooks/create-user.yaml
    ansible.builtin.user:
      name: piotr
      update_password: always
      password: "{{ new_password | password_hash('sha512') }}"
